### PR TITLE
fixes #1

### LINKED ISSUE #1: Error installing from github
This project looks great! I wanted to test it updating from version 3.2.2 to 3.2.3.

Unfortunately, I'm getting an error right off the bat:
```
> install_github("andreacirilloac/updateR")
Downloading GitHub repo andreacirilloac/updateR@master
from URL https://api.github.com/repos/andreacirilloac/updateR/zipball/master
Installing updateR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/st/17pmrjw918357qh9084cmt1m0000gn/T/Rtmpfua4so/devtoolsb211744b188d/AndreaCirilloAC-updateR-8f9f8fb'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘updateR’ ...
** R
Error in parse(outFile) : 
  /private/var/folders/st/17pmrjw918357qh9084cmt1m0000gn/T/Rtmpfua4so/devtoolsb211744b188d/AndreaCirilloAC-updateR-8f9f8fb/R/up:1:97: unexpected ')'
1: updateR <- function(admin_password = "", page_source = "https://cran.rstudio.com/bin/macosx/" ) )
                                                                                                    ^
ERROR: unable to collate and parse R files for package ‘updateR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/updateR’
Error: Command failed (1)
```

So I tried cloning the repo and building the package through Rstudio. Same error. 

I don't know enough about building packages to understand this error - but let me know if I can help with more testing!

### PR DESCRIPTION
**Pull request by RobertMyles**
This commit fixes the confusion in Issue #3 by printing a "please restart R" message. Also updates the README to make a few things clearer. 

P.s. Thought about submitting this to CRAN, Andrea?

### CODE REVIEW

**Comment by RobertMyles** [comment]
This was originally tagged as fixing issue number 1, sorry! I thought there was only one issue. So it fixes #2 .

**Comment by AndreaCirilloAC** [comment]
Hi Robert, really thank you for your pull request!
I am definitely going to merge it 👍 but I would like to resonate a bit more on the "restart version" suggestion: did you actually fixed the problem just restarting? I have tried but it actually still shows me 3.3.0 which is 0.0.3 versions behind the current version.

I guess the problem lies within the installation of the downloaded package, since the piece of code until the download of the new R version from cran.erstudio.com/bin/... works smoothly and actually downloads the package.
I think we should look to this piece of the script:
```
command           <- paste("echo " , admin_password, "| sudo -S installer -pkg ", filename_quoted , " -target / -verbose")
system(command)
```
thank you once more, hope you will further contribute to the package development :)

**Comment by RobertMyles** [comment]
Ok, Andrea, I think that's a good idea, there must be something going wrong with the installation part. I might be able to have a look at it today, let's see!

**Comment by AndreaCirilloAC** [comment]
this sounds great! and once this will be fixed we can definitely start thinking about submitting it to CRAN.
thank you once more

**Pull request merged**
